platform :ios, '11.0'
use_modular_headers!

target 'swift_app_with_pod_no_use_frameworks' do

  pod 'AFNetworking'
  pod 'AgoraAudio_iOS'
  pod 'Alamofire'
  pod 'AliyunOSSiOS'
  pod 'AMScrollingNavbar'
  pod 'AnimatedCollectionViewLayout'
  pod 'AnyImageKit'
  pod 'Aspects'
  pod 'Bagel'
  pod 'BarcodeScanner'
  pod 'BlocksKit'
  pod 'Bugly'
  pod 'BulletinBoard'
  pod 'Cartography'
  pod 'Charts'
  pod 'CocoaAsyncSocket'
  pod 'CocoaLumberjack'
  pod 'CocoaLumberjack/Swift'
  pod 'CoconutKit'
  pod 'CryptoSwift'
  pod 'DropDown'
  pod 'Eureka'
  pod 'FBAEMKit'
  pod 'FBMemoryProfiler'
  pod 'FBRetainCycleDetector'
  pod 'FDFullscreenPopGesture'
  pod 'FileKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'fishhook'
  pod 'FLAnimatedImage'
  pod 'FLEX'
  pod 'FMDB'
  pod 'FSCalendar'
  pod 'FSPagerView'
  pod 'GrowingAutoTrackKit'
  pod 'GrowingCoreKit'
  pod 'InputBarAccessoryView'
  pod 'Instructions'
  pod 'IQKeyboardManager'
  pod 'JLRoutes'
  pod 'JRSwizzle'
  pod 'JTAppleCalendar'
  pod 'JWT'
  pod 'JXPagingView/Paging'
  pod 'JXSegmentedView'
  pod 'KeychainAccess'
  pod 'Kingfisher'
  pod 'KingfisherWebP'
  pod 'Koloda'
  pod 'Lantern'
  pod 'Loading'
  pod 'LookinServer'
  pod 'lottie-ios'
  pod 'LTMorphingLabel'
  pod 'Macaw'
  pod 'Masonry'
  pod 'Material'
  pod 'MBProgressHUD'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'MLeaksFinder'
  pod 'MMKV'
  pod 'MonkeyKing'
  pod 'Moya'
  pod 'MTAppenderFile'
  pod 'MTHawkeye'
  # pod 'Nimble'
  pod 'Nuke'
  pod 'NVActivityIndicatorView'
  pod 'ObjectMapper'
  pod 'OHHTTPStubs'
  pod 'PanModal'
  pod 'Permission'
  pod 'Permission/Microphone'
  pod 'Permission/Photos'
  pod 'PhoneNumberKit'
  pod 'PPBadgeViewSwift'
  pod 'PromiseKit'
  pod 'QMUIKit'
  # pod 'Quick'
  pod 'R.swift'  
  pod 'ReachabilitySwift'
  pod 'ReactiveObjC'
  pod 'Realm'
  pod 'RealmSwift'
  pod 'ReSwift'
  pod 'Reveal-SDK'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SDWebImage'
  pod 'Sentry'
  pod 'SideMenu'
  pod 'Siren'
  pod 'SkeletonView'
  pod 'SnapKit'
  pod 'Sourcery'
  pod 'SQLite.swift'
  pod 'Starscream'
  pod 'Surge'
  pod 'SVProgressHUD'
  pod 'SwiftDate'
  pod 'SwiftEntryKit'
  pod 'SwifterSwift'
  pod 'SwiftMessages'
  pod 'SwiftNIO'
  pod 'SwiftRichString'
  pod 'SwiftyBeaver'
  pod 'SwiftyJSON'
  pod 'SwiftyStoreKit'
  pod 'SwipeCellKit'
  pod 'TensorFlowLiteTaskText'
  pod 'TextFieldEffects'
  pod 'Texture'
  pod 'TOCropViewController'
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMPush'
  pod 'ViewAnimator'
  pod 'WKWebViewJavascriptBridge'
  pod 'YYCache'
  pod 'YYImage'
  pod 'YYImage/WebP'
  pod 'YYModel'
  pod 'YYText'
  pod 'ZipArchive'
  pod "AMPopTip"
  pod "InAppPurchase"
  pod "NSAttributedStringBuilder13"

end

post_install do |installer|
  fix_xcode_12_5_compile_error
end

def fix_xcode_12_5_compile_error
  force_replace_file("Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm",
  "layoutCache[currentClass] = ivars;",
  "layoutCache[(id)currentClass] = ivars;")
end

def force_replace_file(file, origin_content, replace_content)
  unless File.exist? file
      return
  end

  content = File.read(file)

  if content.include? replace_content
      return
  end

  unless content.include? origin_content
      return
  end

  unless system "chmod 777 #{file}"
      return
  end

  content = content.gsub(origin_content, replace_content)

  File.write(file, content)
end
