platform :ios, '11.0'
use_frameworks!

target 'swift_app_with_pod_use_frameworks' do

  pod 'AgoraAudio_iOS'
  pod 'AliyunOSSiOS'
  # pod 'AnyImageKit'
  # pod 'Bagel'
  pod 'Bugly'
  pod 'CocoaLumberjack/Swift'
  pod 'FDFullscreenPopGesture'
  pod 'FileKit'
  pod 'JXPagingView/Paging'
  pod 'JXSegmentedView'
  pod 'Kingfisher'
  # pod 'KingfisherWebP'
  pod 'Lantern'
  pod 'Loading'
  pod 'LookinServer'
  pod 'MBProgressHUD'
  pod 'MJExtension'
  # pod 'MMKV'
  pod 'MonkeyKing'
  pod 'PanModal'
  pod 'Permission'
  pod 'Permission/Microphone'
  pod 'Permission/Photos'
  pod 'PPBadgeViewSwift'
  # pod 'QMUIKit'
  pod 'R.swift'  
  # pod 'RealmSwift'
  pod 'Reveal-SDK'
  pod 'SwifterSwift'
  pod 'SwiftRichString'
  pod 'SwipeCellKit'
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMPush'
  # pod 'WKWebViewJavascriptBridge'
  pod 'YYText'
  pod "AMPopTip"
  pod "InAppPurchase"
  pod "NSAttributedStringBuilder13"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

